parameters:
  linestorm.content.component.comment.class: LineStorm\CommentComponentBundle\Component\CommentComponent

services:
  linestorm.content.component.comment:
    class: %linestorm.content.component.comment.class%
    tags:
      - { name: linestorm.content.component }

#  linestorm.content.component.article.form:
#        class: LineStorm\ArticleComponentBundle\Form\ArticleType
#        arguments: [@linestorm.cms.model_manager]
#        tags:
#            - { name: form.type, alias: linestorm_component_article }
